# Generated by Django 5.2.12 on 2026-03-18 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_customuser_last_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='avatar_url',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_2fa_enabled',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='two_factor_secret',
        ),
    ]
