# Generated by Django 5.2.12 on 2026-03-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_customuser_last_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='display_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
