# Generated by Django 5.2.12 on 2026-03-18 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_remove_customuser_avatar_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_profile_complete',
        ),
    ]
