# Generated by Django 5.2.12 on 2026-03-27 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_alter_customuser_display_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardResetSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('expert', 'Expert'), ('extreme', 'Extreme')], max_length=20, unique=True)),
                ('last_reset', models.DateTimeField(auto_now=True)),
                ('next_reset', models.DateTimeField()),
                ('previous_champion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_type', models.CharField(choices=[('first_win_online', 'First Win'), ('speedster_easy', 'Speedster - Easy'), ('speedster_medium', 'Speedster - Medium'), ('speedster_hard', 'Speedster - Hard'), ('speedster_expert', 'Speedster - Expert'), ('speedster_extreme', 'Speedster - Extreme'), ('on_fire_5x', 'On Fire - 5x'), ('on_fire_10x', 'On Fire - 10x'), ('on_fire_25x', 'On Fire - 25x'), ('graduate_offline', 'Graduate - Offline'), ('graduate_online', 'Graduate - Online'), ('star', 'Star'), ('king_easy', 'King - Easy'), ('king_medium', 'King - Medium'), ('king_hard', 'King - Hard'), ('king_expert', 'King - Expert'), ('king_extreme', 'King - Extreme')], max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('progress', models.IntegerField(default=0)),
                ('target', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-earned_at'],
                'unique_together': {('user', 'achievement_type')},
            },
        ),
    ]
