# Generated by Django 5.2.12 on 2026-04-03 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_leaderboardresetschedule_achievement'),
        ('user_app', '0006_remove_customuser_is_profile_complete'),
    ]

    operations = [
    ]
